{{- if and .Values.redis.openwebui.enabled (not .Values.redis.openwebui.external.enabled) }}
{{ include "inferencehub.redis.deployment" (dict "app" "openwebui" "redis" .Values.redis.openwebui "context" .) }}
{{- end }}
---
{{- if and .Values.redis.litellm.enabled (not .Values.redis.litellm.external.enabled) }}
{{ include "inferencehub.redis.deployment" (dict "app" "litellm" "redis" .Values.redis.litellm "context" .) }}
{{- end }}
