{{- if and .Values.redis.enabled (not .Values.redis.external.enabled) .Values.redis.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inferencehub.fullname" . }}-redis-secret
  namespace: {{ include "inferencehub.namespace" . }}
  labels:
    {{- include "inferencehub.redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.auth.password | quote }}
{{- end }}
