apiVersion: v1
kind: Service
metadata:
  name: {{ include "inferencehub.fullname" . }}-openwebui
  namespace: {{ include "inferencehub.namespace" . }}
  labels:
    {{- include "inferencehub.openwebui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openwebui.service.type }}
  selector:
    {{- include "inferencehub.openwebui.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.openwebui.service.port }}
      targetPort: {{ .Values.openwebui.service.targetPort }}
      protocol: TCP
      name: http
