apiVersion: v1
kind: Service
metadata:
  name: {{ include "inferencehub.fullname" . }}-litellm
  namespace: {{ include "inferencehub.namespace" . }}
  labels:
    {{- include "inferencehub.litellm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.litellm.service.type }}
  selector:
    {{- include "inferencehub.litellm.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.litellm.service.port }}
      targetPort: {{ .Values.litellm.service.targetPort }}
      name: http
